name: Deploy

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & Push image
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          STORYBLOK_TOKEN: ${{ secrets.STORYBLOK_TOKEN }}
        run: |
          docker build \
            --build-arg SUPABASE_URL="$SUPABASE_URL" \
            --build-arg SUPABASE_KEY="$SUPABASE_KEY" \
            --build-arg STORYBLOK_TOKEN="$STORYBLOK_TOKEN" \
            --build-arg STORYBLOK_VERSION=published \
            --build-arg STORYBLOK_REGION=eu \
            -t ghcr.io/matteo-nossro/asc-escalade-clean:latest .
          docker push ghcr.io/matteo-nossro/asc-escalade-clean:latest

      - name: Deploy via Portainer webhook
        run: curl -X POST "${{ secrets.PORTAINER_WEBHOOK_URL }}"

      - name: Nettoyage
        if: always()
        run: docker image prune -f
